name       : protonvpn-nm-lib
version    : 3.11.0
release    : 4
source     :
    - https://github.com/ProtonVPN/protonvpn-nm-lib/archive/refs/tags/3.11.0.tar.gz : c957d92ac435a20af8274ba60dcafd9b067753dfece33702333fb7323f0017bc
license    : GPL-3.0-or-later
component  : network.utils
summary    : ProtonVPN network manager library.
description: |
    ProtonVPN network manager library.
builddeps  :
    - pyxdg
    - python-distro
    - python-jinja
    - python-keyring
    - python-pythondialog
    - python-gobject
rundeps    :
    - proton-python-client
    - networkmanager-openvpn
    - python-keyring
    - gnome-keyring
    - python-distro
    - python-jinja
    - python-dbus
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
