name       : protonvpn-nm-lib
version    : 3.16.0
release    : 8
source     :
    - https://github.com/ProtonVPN/protonvpn-nm-lib/archive/refs/tags/3.16.0.tar.gz : 9edf705d435b65d54c7224d4bc853b4b7e02a228a57264083b2776b8424aee36
license    : GPL-3.0-or-later
component  : network.utils
summary    : ProtonVPN network manager library.
description: |
    ProtonVPN network manager library.
builddeps  :
    - pyxdg
    - python-distro
    - python-jinja
    - python-keyring
    - python-gobject
rundeps    :
    - networkmanager-openvpn
    - proton-python-client
    - python-distro
    - python-keyring
    - python-jinja
    - python-systemd
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
