name       : protonvpn-nm-lib
version    : 3.14.0
release    : 7
source     :
    - https://github.com/ProtonVPN/protonvpn-nm-lib/archive/refs/tags/3.14.0.tar.gz : 42f03015957b53125124bfc2e5ec77536023b6c49410b861833a08a4912324d2
license    : GPL-3.0-or-later
component  : network.utils
summary    : ProtonVPN network manager library.
description: |
    ProtonVPN network manager library.
builddeps  :
    - pyxdg
    - python-distro
    - python-jinja
    - python-keyring
    - python-gobject
rundeps    :
    - networkmanager-openvpn
    - proton-python-client
    - python-distro
    - python-keyring
    - python-jinja
    - python-systemd
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
